# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

import os
import pathlib
import pandas as pd
from snakemake.remote.S3 import RemoteProvider as S3RemoteProvider
from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider
from snakemake.utils import validate

S3 = S3RemoteProvider()

sys.path.insert(0, ".")
from lib import target_construction as tc

shell.executable("/bin/bash")
shell.prefix("set -euo pipefail; ")


configfile: "config/config.yaml"


validate(config, "../schema/global_config_schema.yaml")

tempDir = "temp"
manifest = config["manifest"]
manifest = pd.read_csv(manifest, sep="\t").set_index("experimental_dataset", drop=False)
reference_build = config["genome-build"]


validate(manifest, "../schema/manifest_schema.yaml")


TARGETS = ["results/reports/control_validation.html"]


rule all:
    input:
        TARGETS,


include: "rules/acquire_data.smk"
include: "rules/happy.smk"
include: "rules/reference_data.smk"
include: "rules/vcfeval.smk"
