## This workflow is structured slightly differently than usual.
## There are three manifests:
## - a set of experimental vcfs, with unique aliases
## - a set of reference sample vcfs, with unique aliases
## - a set of comparisons between experimental and reference vcfs, referred to by their aliases from the other two manifests
## This structure is a little complicated, but is designed to keep the configuration as streamlined as possible.
## Unfortunately, these kinds of comparisons are inherently a little messy.

experiment-manifest: "config/manifest_experiment.tsv"
## the GIAB links were extracted from the Octopus publication, supplemental note 1, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7611855/#SD1
reference-manifest: "config/manifest_reference.tsv"
comparisons-manifest: "config/manifest_comparisons.tsv"
happy-bedfiles-per-stratification: 1
genome-build: "grch38"
sv-toolname: "truvari"


sv-settings:
  merge-experimental-before-comparison: no
  merge-reference-before-comparison: no
  svanalyzer:
    maxdist: 100000
    normshift: 0.2
  svdb:
    bnd-distance: 10000
    overlap: 0.6


## Stratification regions are suggested for use with hap.py style analysis. All thanks to Justin Zook lol
genomes:
  grch38:
    fasta: "https://ftp-trace.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz"
    confident-regions:
      all:
        bed: "resources/grch38.bed"
      NA12878_high_confidence:
        bed: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/NA12878_HG001/latest/GRCh38/HG001_GRCh38_1_22_v4.2.1_benchmark.bed"
        inclusion: "NA12878"
      NA24385_high_confidence:
        bed: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed"
        inclusion: "NA24385"
    stratification-regions:
      ftp: "ftp-trace.ncbi.nlm.nih.gov"
      dir: "ReferenceSamples/giab/release/genome-stratifications/v3.3/GRCh38@all"
      all-stratifications: "GRCh38-all-stratifications.tsv"
      region-labels: "resources/v3.3.region-labels.tsv"
      region-inclusions:
        "*": ".*"
        "alldifficultregions": ".*"
        "alllowmapandsegdupregions": ".*"
        "notinalllowmapandsegdupregions": ".*"
  grch37:
    fasta: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/references/GRCh37/hs37d5.fa.gz"
    confident-regions:
      all:
        bed: "resources/grch37.bed"
    stratification-regions:
      ftp: "ftp-trace.ncbi.nlm.nih.gov"
      dir: "ReferenceSamples/giab/release/genome-stratifications/v3.3/GRCh37@all"
      all-stratifications: "GRCh37-all-stratifications.tsv"
      region-labels: "resources/v3.3.region-labels.tsv"
      region-inclusions:
        "*": ".*"
        "alldifficultregions": ".*"
        "alllowmapandsegdupregions": ".*"
        "notinalllowmapandsegdupregions": ".*"
